kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "flagr.fullname" . }}
  labels:
    {{- include "flagr.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.environmentVariables }}
{{ $key | quote | indent 1}}: {{ $val | quote }}
{{- end}}
